# Generated by Django 4.0.3 on 2022-03-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.SlugField(blank=True, default=None)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='newsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('url', models.URLField()),
                ('urlToImage', models.URLField(max_length=1000)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsBackend.sourcemodel')),
            ],
        ),
    ]
