# Generated by Django 4.0.3 on 2022-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='img_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='news_url',
            new_name='urlToImage',
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
