# Generated by Django 4.0.3 on 2022-03-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBackend', '0002_rename_img_url_newsmodel_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='urlToImage',
            field=models.URLField(max_length=1000),
        ),
    ]
