# Generated by Django 4.0.3 on 2022-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBackend', '0003_alter_newsmodel_description_alter_newsmodel_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcemodel',
            old_name='source_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='sourcemodel',
            name='source_id',
        ),
        migrations.AlterField(
            model_name='sourcemodel',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False, unique=True),
        ),
    ]
